// DO NOT EDIT.
// Code is generated by protoc-gen-tfschema {{ .Version }}
// Using protoc {{ .ProtocVersion }}

package {{ .PackageName }}

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

{{ range $name, $resource := .Resources }}
// Type full name: {{ .FullName }}
func Schema{{ $name }}() map[string]*schema.Schema {
	return {{ template "schemaMap" .Schema -}}
}
{{ end }}

{{- define "schemaMap" -}}
map[string]*schema.Schema {
{{- range $name, $schema := . }}
	// {{ .FullName }}
	"{{ SnakeCase $name }}": {{ template "schema" . }}
{{- end }}
}
{{- end -}}

{{- define "schema" -}}
{
	Type: {{ .Type }},
	{{- if .Required }}
	Required: true,
	{{- else }}
	Optional: true,
	{{- end }}

	{{- if .MaxItems }}
	MaxItems: {{ .MaxItems }},
	{{- end }}

	{{- if .ValidateFunc }}
	ValidateFunc: {{ .ValidateFunc }},
	{{- end }}

	{{- template "elem" .Elem }}
},
{{- end -}}

{{- define "nestedSchema" -}}
{
	Type: {{ .Type }},
	{{- if .Elem }}
	{{- template "elem" .Elem }}
	{{- end }}
},
{{- end -}}

{{ define "elem" -}}
{{- if . }}
{{- if IsSchema . }}
Elem: &schema.Schema {{- template "nestedSchema" . }}
{{- else }}
Elem: &schema.Resource {
	Schema: Schema{{- . -}}(),
},
{{- end }}
{{- end }}
{{ end }}