// DO NOT EDIT.
// Code is generated by protoc-gen-tfschema 0.0.2
// Using protoc v3.14.0
// Source: types.proto

package tfschema

import (
	"github.com/hashicorp/terraform/helper/schema"
	"github.com/hashicorp/terraform/helper/validation"
)

// proto type full name: types.Metadata
func schemaMetadata() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"Name": {
			Optional: true,
			Type:     schema.TypeString,
		},
		"Namespace": {
			Optional: true,
			Type:     schema.TypeString,
		},
		"Description": {
			Optional: true,
			Type:     schema.TypeString,
		},
		"Labels": {
			Optional: true,
			Type:     schema.TypeMap,
		},
		"Expires": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"ID": {
			Optional: true,
			Type:     schema.TypeInt,
		},
	}
}

// proto type full name: types.UserV2
func schemaUserV2() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"Kind": {
			Optional: true,
			Type:     schema.TypeString,
		},
		"SubKind": {
			Optional: true,
			Type:     schema.TypeString,
		},
		"Version": {
			Optional: true,
			Type:     schema.TypeString,
		},
		"Metadata": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"Spec": {
			Optional: true,
			Type:     schema.TypeList,
		},
	}
}

// proto type full name: types.UserSpecV2
func schemaUserSpecV2() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"OIDCIdentities": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"SAMLIdentities": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"GithubIdentities": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"Roles": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"Traits": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"Status": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"Expires": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"CreatedBy": {
			Optional: true,
			Type:     schema.TypeList,
		},
		"LocalAuth": {
			Optional: true,
			Type:     schema.TypeList,
		},
	}
}
